- hosts: 10.1.1.10
  tasks:
    - name: Check Hostname
      command: hostname
      register: hostname
      
    - name: Print Hostname
      debug:
        msg: "Hostname is: {{ hostname.stdout }}"
      
    - name: Check IP Address & Route
      shell: ip addr | grep eth0
      register: ipaddress
      
    - name: Print IP Address
      debug:
        msg: "IP Address: {{ipaddress.stdout }}"   
      
    - name: Check MAIL SSL Cert
      shell: echo "quit" | openssl s_client -showcerts -connect wsc17.cloud:465 | grep issuer
      register: mailssl
    
    - name: Print MAIL SSL Cert
      debug:
        msg: "Mail ssl cert is: {{ mailssl.stdout }}"
      
      
      
