- hosts: 10.1.1.10
  tasks:
    - name: Check Hostname
      shell: hostname
      register: hostname
      
    - name: Check IP Address & Route
      shell: |
        ip addr
        ip route
      register: ipaddressroute
      
    - name: Check Keyboard & Locale
      shell: ||
        cat /etc/default/keyboard | grep XKBLAYOUT
        cat /etc/default/locale
      register: keyboardlocale
      
    - name: Print Hostname, IP Address, Route, Keyboard, & Locale
      debug:
        msg: "Hostname is: {{ hostname.stdout }}"
        msg: "IP Address & Route are: {{ipaddressroute.stdout }}"
        msg: "Keyboard & Locale are: {{keyboardlocale.stdout }}"

    - name: Check MAIL SSL Cert
      shell: echo "quit" | openssl s_client -showcerts -connect wsc17.cloud:465 | grep issuer
      register: mailssl
    
    - name: Print MAIL SSL Cert
      debug:
        msg: "Mail ssl cert is: {{ mailssl.stdout }}"
      
      
      
