- hosts: 10.1.1.10
  tasks:
    - name: Check Hostname
      command: hostname
      register: hostname
      
    - name: Check IP Address & Route
      command: "{{ item }}"
      with_items:
        - ip addr
        - ip route
      register: ipaddressroute
      
    - name: Print Hostname, IP Address, Route, Keyboard, & Locale
      debug:
        msg: "Hostname is: {{ hostname.stdout }}"
        msg: "IP Address & Route are: {{ipaddressroute.stdout }}"

    - name: Check MAIL SSL Cert
      command: echo "quit" | openssl s_client -showcerts -connect wsc17.cloud:465 | grep issuer
      register: mailssl
    
    - name: Print MAIL SSL Cert
      debug:
        msg: "Mail ssl cert is: {{ mailssl.stdout }}"
      
      
      
